name: fedva
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - pip
  - numpy=1.21
  - scikit-learn=0.24
  - matplotlib=3.5
  - pillow
  - scipy
  - pip:
      - charset-normalizer==3.4.1
      - cycler==0.11.0
      - fonttools==4.38.0
      - idna==3.10
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - loguru==0.3.2
      - packaging==24.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - requests==2.31.0
      - six==1.17.0
      - torch==1.13.1
      - torchvision==0.14.1
      - typing-extensions==4.7.1
      - urllib3==2.0.7
