name: poisonfl
channels:
  - defaults
dependencies:
  - python=3.7.16
  - pip=22.3.1
  - pip:
      - torch==1.13.1+cu117
      - torchvision==0.14.1+cu117
      - numpy==1.17.0
      - matplotlib==3.5.3
      - scikit-learn==0.21.3
      - scipy==1.7.3
      - requests==2.31.0
      - loguru==0.3.2
